name = "BayesianStats"
uuid = "edf80a36-dbf3-449e-b037-ec14e76cb7d2"
authors = ["James Alster <jamesalster2@gmail.com>"]
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Distributions = "0.25.113"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
